#pragma once

#include "EightWinds/VulkanHeader.h"

#include <cstdint>

namespace EWE{
    struct PipelineParamPack{
        VkPipeline pipe;
        VkPipelineLayout layout;
        VkPipelineBindPoint bindPoint;
    };
    struct VertexDrawParamPack{
        uint32_t vertexCount;
        uint32_t instanceCount;
        uint32_t firstVertex;
        uint32_t firstInstance;
    };
    struct IndexDrawParamPack{
        uint32_t indexCount;
        uint32_t instanceCount;
        uint32_t firstIndex;
        uint32_t vertexOffset;
        uint32_t firstInstance;
    };
    struct LabelParamPack{
        const char* name;
        float red;
        float green;
        float blue;
    };
    struct DispatchParamPack{
        uint32_t x;
        uint32_t y;
        uint32_t z;
    };
    struct ViewportScissorParamPack{
        VkViewport viewport;
        VkRect2D scissor;
    };
    struct ViewportScissorWithCountParamPack{
        static constexpr uint32_t ArbitraryViewportCountLimit = 10;
        static constexpr uint32_t ArbitraryScissorCountLimit = 10;
        //lets set an arbitrary limit to 10
        VkViewport viewports[ArbitraryViewportCountLimit];
        VkRect2D scissors[ArbitraryScissorCountLimit];
        uint32_t currentViewportCount = 0;
        uint32_t currentScissorCount = 0;
    };
    struct BlitParamPack {
        VkImage srcImage;
        VkImageLayout srcLayout;
        VkImage dstImage;
        VkImageLayout dstLayout;
        VkImageBlit blitParams; //theres a better name for this idk what it is
        VkFilter filter;
    };

    struct CommandInstruction{
        enum class Type : uint8_t {
            BindPipeline,

            //descriptor needs to be expanded to handle images and buffers
            BindDescriptor,

            PushConstant, 

            BeginRender,
            EndRender,

            Draw,
            DrawIndexed,
            Dispatch,

            //if more regions are needed per blit (currently hardlocked to 1)
            //a separate command will be needed. idk if that'll be necessary?
            //dont write the params for blit directly to the deferred_pack, write it to an index
            Blit,

            //the queue can be taken from the command buffer
            //the submit info can be generated by the rendergraph
            Present,

            //PipelineBarrier,

            //dynamicstate
            DS_ViewportScissor,
            DS_ViewportScissorWithCount,

            BeginLabel,
            EndLabel,

            //control flow
            If,

            //im not sure if i want to do more advanced control flow yet
            LoopBegin,

            Switch,
            Case,
            Default,

            //these 3 dont have any independent functionality
            EndIf,
            LoopEnd,
            SwitchEnd,

            //im only going to implement vp scissor for the moment
            DS_LineWidth,
            DS_DepthBias,
            DS_BlendConstants,
            DS_DepthBounds,
            DS_StencilCompareMask,
            DS_StencilWriteMask,
            DS_StencilReference,
            DS_CullMode,
            DS_FrontFace,
            DS_PrimitiveTopology,
            DS_DepthTestEnable,
            DS_DepthWriteEnable,
            DS_DepthCompareOp,
            DS_DepthBoundsTestEnable,
            DS_StencilTestEnable,
            DS_StencilOp,
            DS_RasterizerDiscardEnable,
            DS_DepthBiasEnable,
            DS_PrimitiveRestartEnable,
            //wtf is a stipple
            //DS_LineStipple,

        };

        Type type;
        std::size_t paramOffset;

        CommandInstruction(Type type, std::size_t offset)
            : type(type), paramOffset(offset) 
        {}

        static uint64_t GetParamSize(Type type) noexcept;
    };

} //namespace EWE