#include "EightWinds/RenderGraph/RenderGraph.h"
#include "EightWinds/VulkanHeader.h"

namespace EWE{


    RenderGraph::RenderGraph(
        std::filesystem::path const& _name,
        LogicalDevice& _logicalDevice, Swapchain& _swapchain, 
        Queue& _renderQueue, Queue& _computeQueue,
        SubmissionTask& _graphics_stc_task,
        SubmissionTask& _compute_stc_task
    )
    : name{_name},
        logicalDevice{_logicalDevice},
        swapchain{_swapchain},
        renderQueue{_renderQueue}, computeQueue{_computeQueue},
        graphics_stc_task{_graphics_stc_task},
        compute_stc_task{_compute_stc_task},
        presentBridge{logicalDevice, swapchain.presentQueue},
        //presentSubmission{ swapchain, swapchain.presentQueue },
        present_wait_semaphore_data{
            VkSemaphoreSubmitInfo{
                .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                .pNext = nullptr,
                .semaphore = VK_NULL_HANDLE,
                .value = 0,
                .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                .deviceIndex = 0
            }
        },
        presentInfo{
            VkPresentInfoKHR{
                .sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,
                .pNext = nullptr,
                .waitSemaphoreCount = 1,
                .swapchainCount = uint32_t(1),
                .pSwapchains = &swapchain.activeSwapchain,
                .pImageIndices = &swapchain.imageIndex,
                .pResults = &presentResult
            }
        },
        semaphores{0, logicalDevice},
        stc_management{
            logicalDevice,
            renderQueue, computeQueue
        },
        current_stc_manager{stc_management.GetNext()}
        //binary_semaphores{0, logicalDevice}
    {
        auto& stc_m = *stc_management.begin();
    
#if EWE_DEBUG_BOOL
        Log::Warning("need visual feedback for rendergraph\n");

        Log::Warning("need to see task to task ordering, dependencies, bridges\n");
        Log::Warning("need to see each barrier generated by bridges, each resource in use, each pipe in use, EVERYTHING\n");
#endif
        
    }

    bool RenderGraph::Acquire(uint8_t frameIndex){
        return swapchain.AcquireNextImage(frameIndex);
    }

    void RenderGraph::Execute(uint8_t frameIndex) {
        auto frame_stc_manager = current_stc_manager;
        current_stc_manager = stc_management.GetNext();
        frame_stc_manager->CollectSTCs();

        UpdateSemaphores(frameIndex, *frame_stc_manager);

        const bool submitting_compute_stc = frame_stc_manager->CheckSize(Queue::Compute);
        const bool submitting_graphics_stc = frame_stc_manager->CheckSize(Queue::Graphics);
        if(submitting_compute_stc){
            compute_stc_task.packaged_tasks.clear();
            compute_stc_task.packaged_tasks.push_back(frame_stc_manager->compute_task);
            compute_stc_task.Execute(frameIndex);
            computeQueue.Submit2(compute_stc_task.submitInfo[frameIndex].Expand());
        }
        if(submitting_graphics_stc){
            graphics_stc_task.packaged_tasks.clear();
            graphics_stc_task.packaged_tasks.push_back(frame_stc_manager->graphics_task);
            graphics_stc_task.Execute(frameIndex);
            auto& stc_subInfo = graphics_stc_task.submitInfo[frameIndex];
            renderQueue.Submit2(stc_subInfo.Expand());
        }

        frame_stc_manager->UpdateResources();
        stc_management.Return(frame_stc_manager);

        for (std::size_t i = 0; i < execution_order.size(); i++) {
            std::vector<VkSubmitInfo2> subInfos{};
            Queue* queue = nullptr;
            for(auto& ind_sub : execution_order[i]) {
                //populate sumibssion
                //potentially assert each queue is identical per submission group
                queue = ind_sub->queue;
                ind_sub->Execute(frameIndex);

                subInfos.push_back(ind_sub->submitInfo[frameIndex].Expand());
            }
            EWE_ASSERT(queue != nullptr);
            for (auto& subIn : subInfos) {
                EWE_ASSERT(subIn.commandBufferInfoCount > 0);
            }

            if (i == (execution_order.size() - 1)) {
                queue->Submit2(subInfos.size(), subInfos.data(), swapchain.inFlightFences[frameIndex]);
            }
            else {
                queue->Submit2(subInfos.size(), subInfos.data(), VK_NULL_HANDLE);
            }
        }

        presentInfo[frameIndex].pSwapchains = &swapchain.activeSwapchain;
        swapchain.presentQueue.Present(presentInfo[frameIndex]);
        //could iterate thru each result in presentInfo
    }

    void RenderGraph::UpdateSwapImage(uint8_t frameIndex){
        auto& swapImage = swapchain.GetCurrentImage();
        swapImage.data.layout = VK_IMAGE_LAYOUT_UNDEFINED;

        for(auto& simg : swap_image_instances){
            ChangeResource(*simg.task, simg.res_index, &swapImage, frameIndex);
        }
        presentBridge.UpdateSrcData(frameIndex);
    }

    void RenderGraph::ClearAllBarriers(uint8_t frameIndex) {
        for (auto& task : tasks) {
            task->prefix.Clear(frameIndex);
            task->suffix.Clear(frameIndex);
        }
    }
    void RenderGraph::RecreateBarriers(uint8_t frameIndex) {
        ClearAllBarriers(frameIndex);
        syncManager.PopulateAffixes(frameIndex);

        for (auto& task : tasks) {
            auto& pref_barr = task->prefix.barriers[frameIndex];
            pref_barr.FixPointers();
            auto& suff_barr = task->suffix.barriers[frameIndex];
            suff_barr.FixPointers();
        }
    }

    void RenderGraph::InitializeSemaphores(){

        //each ind_sub needs an individual signal, but each group can re-use semaphores
        {
            std::size_t max_width = 0;
            for(std::size_t i = 0; i < (execution_order.size() - 1); i++){
                //the back uses binary semaphores, so we don't need to cosnider the size for timeline semapohres
                auto& sub_group = execution_order[i];
                if(sub_group.size() > max_width){
                    //i lost the context for this, previously it was max_width = sub_group.size
                    max_width = std::max(max_width, sub_group.size());
                }
            }
            max_width = std::max(max_width, std::size_t(1));
            if(max_width != semaphores[0].Size()){
                for_each_frame{
                    semaphores[frame].ClearAndResize(max_width, logicalDevice);
                }
            }

            //i need to do some manual binary semaphore creation here
            //the binary semaphores aren't per flight, they're per swap image
            EWE_ASSERT(execution_order.back().size() == 1);

            for_each_frame{
                present_wait_raw_semaphore_data[frame].clear();
            }
        }

        std::size_t present_image_used_index = execution_order.size();

        for_each_frame{
            compute_stc_task.submitInfo[frame].signalSemaphores.clear();
            graphics_stc_task.submitInfo[frame].signalSemaphores.clear();
            //stcs
            if(execution_order.size() == 0){
                //this is valid
                EWE_ASSERT(false, "not supported yet");
            }
            else{
                graphics_stc_task.submitInfo[frame].signalSemaphores.emplace_back(
                    VkSemaphoreSubmitInfo{
                        .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                        .pNext = nullptr,
                        .semaphore = semaphores[frame][0],
                        .value = 1,
                        .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                        .deviceIndex = 0
                    }   
                );
            }

            for(std::size_t i = 0; i < execution_order.size(); i++){
                auto& sub_group = execution_order[i];
                if(first_graphics_task_group < 0){
                    if(*sub_group[0]->queue == renderQueue){
                        first_graphics_task_group = i;
                    }
                }
                if(first_compute_task_group < 0){
                    if(*sub_group[0]->queue == computeQueue){
                        first_compute_task_group = i;
                    }
                }

                for(std::size_t j = 0; j < sub_group.size(); j++){
                    auto& ind_sub = sub_group[j];
                    ind_sub->submitInfo[frame].waitSemaphores.clear();
                    ind_sub->submitInfo[frame].signalSemaphores.clear();

                    //it'll be one signal per queue that's goign to wait on this
                    //CURRENTLY, i'm only setting up graphics
                    if(i == (execution_order.size() - 1)){
                        ind_sub->submitInfo[frame].signalSemaphores.emplace_back(
                            VkSemaphoreSubmitInfo{
                                .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                                .pNext = nullptr,
                                .semaphore = VK_NULL_HANDLE,//binary_semaphores[frame][j],
                                .value = i + 2,
                                .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                                .deviceIndex = 0
                            }
                        );
                        //present_wait_raw_semaphore_data[frame].push_back(binary_semaphores[frame][j].vkSemaphore);
                    }
                    else{
                        ind_sub->submitInfo[frame].signalSemaphores.emplace_back(
                            VkSemaphoreSubmitInfo{
                                .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                                .pNext = nullptr,
                                .semaphore = semaphores[frame][j],
                                .value = i + 2, //i + 2, the first submission (the STC, not included in execution_groups) is equal to 1
                                .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                                .deviceIndex = 0
                            }
                        );
                    }
                    if(i > 0){
                        auto& prev_sub_group = execution_order[i - 1];
                        for(std::size_t k = 0; k < prev_sub_group.size(); k++){
                            auto& prev_ind_sub = prev_sub_group[k];
                            //when i eventually add more queues, this will need to reflect that
                            //right now, it doesn't consider queues
                            ind_sub->submitInfo[frame].waitSemaphores.emplace_back(&prev_ind_sub->submitInfo[frame].signalSemaphores[0]);
                        }
                    }

                    if(ind_sub->uses_present_image){
                        if(i <= present_image_used_index){
                            present_image_used_index = i;
                            ind_sub->submitInfo[frame].waitSemaphores.emplace_back( 
                                //this is a binary semaphore - waits on acquire
                                //on startup the underlying semaphore will be nullptr, it will be fixed, this is a pointer
                                &present_wait_semaphore_data[frame]
                            );
                        }
                    }
                }
            }

            present_wait_raw_semaphore_data[frame].push_back(swapchain.GetCurrentPresentSemaphore());
            presentInfo[frame].waitSemaphoreCount = present_wait_raw_semaphore_data[frame].size();
            presentInfo[frame].pWaitSemaphores = present_wait_raw_semaphore_data[frame].data();
        }
    }

    void RenderGraph::UpdateSemaphores(uint8_t frameIndex, STC_Submitter& frame_stc_manager) {
        const bool submitting_compute_stc = frame_stc_manager.CheckSize(Queue::Compute);
        const bool submitting_graphics_stc = frame_stc_manager.CheckSize(Queue::Graphics);

        EWE_ASSERT(!submitting_compute_stc, "not ready for compute commands yet");

        if(first_graphics_task_group > 0){
            auto& first_graphics_group = execution_order[first_graphics_task_group];
            const auto stc_receiver_size = first_graphics_group[0]->submitInfo[frameIndex].waitSemaphores.size();
            const auto stc_prev_size = execution_order[first_graphics_task_group - 1][0]->submitInfo[frameIndex].signalSemaphores.size();
            if(stc_receiver_size > stc_prev_size){
                for(auto& current_group_member : first_graphics_group){
                    current_group_member->submitInfo[frameIndex].waitSemaphores.pop_back();
                }
            }
        }
        else if(first_graphics_task_group == 0){
            for(auto& ind_sub : execution_order[0]){
                ind_sub->submitInfo[frameIndex].waitSemaphores.clear();

                //can I just plop this here?
                if(ind_sub->uses_present_image){
                    ind_sub->submitInfo[frameIndex].waitSemaphores.emplace_back( 
                        //this is a binary semaphore - waits on acquire
                        //on startup the underlying semaphore will be nullptr, it will be fixed, this is a pointer
                        &present_wait_semaphore_data[frameIndex]
                    );
                }
            }
        }

        if(first_compute_task_group > 0){
            auto& first_compute_group = execution_order[first_compute_task_group];
            const auto stc_receiver_size = first_compute_group[0]->submitInfo[frameIndex].waitSemaphores.size();
            const auto stc_prev_size = execution_order[first_compute_task_group - 1][0]->submitInfo[frameIndex].signalSemaphores.size();
            if(stc_receiver_size > stc_prev_size){
                for(auto& current_group_member : first_compute_group){
                    current_group_member->submitInfo[frameIndex].waitSemaphores.pop_back();
                }
            }
        }
        else if(first_compute_task_group == 0){
            for(auto& ind_sub : execution_order[0]){
                ind_sub->submitInfo[frameIndex].waitSemaphores.clear();
            }
        }

        if(first_graphics_task_group >= 0){
            auto& sig_sem = graphics_stc_task.submitInfo[frameIndex].signalSemaphores[0];
            if(submitting_graphics_stc){
                auto& first_graphics_group = execution_order[first_graphics_task_group];
                for(auto& ind_sub : first_graphics_group){
                    ind_sub->submitInfo[frameIndex].waitSemaphores.push_back(&sig_sem);
                }
            }
            auto& ref_sem = semaphores[frameIndex][0];
            sig_sem.value = ref_sem.value + 1;
            ref_sem.value++;
        }

        if(first_compute_task_group >= 0){
            auto& sig_sem = compute_stc_task.submitInfo[frameIndex].signalSemaphores[0];             
            if(submitting_compute_stc){
                auto& first_compute_group = execution_order[first_compute_task_group];
                for(auto& ind_sub : first_compute_group){
                    ind_sub->submitInfo[frameIndex].waitSemaphores.push_back(&sig_sem);
                }
            }
            auto& ref_sem = semaphores[frameIndex][0];
            sig_sem.value = ref_sem.value + 1;
            ref_sem.value++;
        }
        

        for(std::size_t i = 0; i < execution_order.size(); i++){
            if(i != (execution_order.size() - 1)){
                auto& sub_group = execution_order[i];
                for(std::size_t j = 0; j < sub_group.size(); j++){
                    auto& ind_sub = sub_group[j];
                    EWE_ASSERT(ind_sub->submitInfo[frameIndex].signalSemaphores[0].semaphore == semaphores[frameIndex][j].vkSemaphore);

                    ind_sub->submitInfo[frameIndex].signalSemaphores[0].value = semaphores[frameIndex][j].value + 1;
                    semaphores[frameIndex][j].value++;
                }
            }
        }

        present_wait_semaphore_data[frameIndex].semaphore = swapchain.GetAcquireSemaphore(frameIndex);
        present_wait_raw_semaphore_data[frameIndex].back() = swapchain.GetCurrentPresentSemaphore();
        execution_order.back()[0]->submitInfo[frameIndex].signalSemaphores[0].semaphore = present_wait_raw_semaphore_data[frameIndex].back();
    }

    template <> 
    void RenderGraph::ResourceOwnershipTransfer(STC_Sub_Package<Image> const& data) {
        //do flip flop storage
        current_stc_manager->image_ownership.push_back(data);
    }
    template<>
    void RenderGraph::ResourceOwnershipTransfer(STC_Sub_Package<Buffer> const& data){
        current_stc_manager->buffer_ownership.push_back(data);
    }
}