#include "EightWinds/RenderGraph/RenderGraph.h"
#include "EightWinds/VulkanHeader.h"

#include <format>

namespace EWE{


    RenderGraph::RenderGraph(LogicalDevice& logicalDevice, Swapchain& swapchain)
        : logicalDevice{logicalDevice},
        swapchain{swapchain},
        presentBridge{logicalDevice, swapchain.presentQueue},
        //presentSubmission{ swapchain, swapchain.presentQueue },
        presentInfo{
            VkPresentInfoKHR{
                .sType = VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,
                .pNext = nullptr,
                .waitSemaphoreCount = 1,
                .swapchainCount = uint32_t(1),
                .pSwapchains = &swapchain.activeSwapchain,
                .pImageIndices = &swapchain.imageIndex,
                .pResults = &presentResult
            }
        },
        present_wait_semaphore_data{
            VkSemaphoreSubmitInfo{
                .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                .pNext = nullptr,
                .semaphore = VK_NULL_HANDLE,
                .value = 0,
                .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                .deviceIndex = 0
            }
        },
        semaphores{0, logicalDevice}//,
        //binary_semaphores{0, logicalDevice}
    {
#if EWE_DEBUG_BOOL
        printf("need visual feedback for this\n");

        printf("need to see task to task ordering, dependencies, bridges\n");
        printf("need to see each barrier generated by bridges, each resource in use, each pipe in use, EVERYTHING\n");
#endif
        
    }

    bool RenderGraph::Acquire(uint8_t frameIndex){
        return swapchain.AcquireNextImage(frameIndex);
    }

    void RenderGraph::Execute(uint8_t frameIndex) {

        UpdateSemaphores(frameIndex);

        for (std::size_t i = 0; i < execution_order.size(); i++) {
            std::vector<VkSubmitInfo2> subInfos{};
            Queue* queue = nullptr;
            for(auto& ind_sub : execution_order[i]) {
                //populate sumibssion
                //potentially assert each queue is identical per submission group
                queue = &ind_sub->queue;
                ind_sub->Execute(frameIndex);

                //if(ind_sub->signal){
                    subInfos.push_back(ind_sub->submitInfo[frameIndex].Expand());
                    //std::copy(signaledSemaphores.end(), ind_sub->submitInfo[frameIndex].signalSemaphores.begin(), ind_sub->submitInfo[frameIndex].signalSemaphores.end());
                    //std::copy(previous.waitSemaphores.begin(), previous.waitSemaphores.end(), std::back_inserter(waitSemaphores));
                //}
                //else{
                //    subInfos.push_back(ind_sub->submitInfo[frameIndex].ExpandWithoutSignal());
                //}
            }
#if EWE_DEBUG_BOOL
            assert(queue != nullptr);
#endif
            for (auto& subIn : subInfos) {
                assert(subIn.commandBufferInfoCount > 0);
            }

            if (i == (execution_order.size() - 1)) {
                queue->Submit2(subInfos.size(), subInfos.data(), swapchain.inFlightFences[frameIndex]);
            }
            else {
                queue->Submit2(subInfos.size(), subInfos.data(), VK_NULL_HANDLE);
            }
        }

        presentInfo[frameIndex].pSwapchains = &swapchain.activeSwapchain;

        /*
        std::vector<std::size_t> temp_debugger{};
        for(std::size_t i = 0; i < presentInfo[frameIndex].waitSemaphoreCount; i++){
            temp_debugger.push_back(reinterpret_cast<std::size_t>(presentInfo[frameIndex].pWaitSemaphores[i]));
            printf(std::format("0x{:x}\n", temp_debugger.back()).c_str());
        }
        */

        VkResult temp_ret = vkQueuePresentKHR(swapchain.presentQueue, &presentInfo[frameIndex]);
        if(temp_ret != VK_SUBOPTIMAL_KHR){
            EWE_VK_RESULT(temp_ret);
        }
        if(presentResult != VK_SUBOPTIMAL_KHR){
            EWE_VK_RESULT(presentResult);
        }
    }

    void RenderGraph::ClearAllBarriers(uint8_t frameIndex) {
        for (auto& task : tasks) {
            task.prefix.Clear(frameIndex);
            task.suffix.Clear(frameIndex);
        }
    }
    void RenderGraph::RecreateBarriers(uint8_t frameIndex) {
        ClearAllBarriers(frameIndex);
        syncManager.PopulateAffixes(frameIndex);

        for (auto& task : tasks) {
            auto& pref_barr = task.prefix.barriers[frameIndex];
            pref_barr.FixPointers();
            auto& suff_barr = task.suffix.barriers[frameIndex];
            suff_barr.FixPointers();
        }
    }

    void RenderGraph::InitializeSemaphores(){

        //each ind_sub needs an individual signal, but each group can re-use semaphores
        {
            std::size_t max_width = 0;
            for(std::size_t i = 0; i < (execution_order.size() - 1); i++){
                //the back uses binary semaphores, so we don't need to cosnider the size for timeline semapohres
                auto& sub_group = execution_order[i];
                if(sub_group.size() > max_width){
                    max_width = sub_group.size();
                }
            }
            if(max_width != semaphores[0].Size()){
                for(uint8_t frame = 0; frame < max_frames_in_flight; frame++){
                    semaphores[frame].ClearAndResize(max_width, logicalDevice);
                }
            }

            //i need to do some manual binary semaphore creation here
            //the binary semaphores aren't per flight, they're per swap image
            EWE_ASSERT(execution_order.back().size() == 1);

            /*
            if(binary_semaphores[0].Size() != execution_order.back().size()){
                for(uint8_t frame = 0; frame < max_frames_in_flight; frame++){
                    binary_semaphores[frame].ClearAndResize(execution_order.back().size(), logicalDevice);
                }
            }
            */
            for(uint8_t frame = 0; frame < max_frames_in_flight; frame++){
                present_wait_raw_semaphore_data[frame].clear();
            }
        }

        std::size_t present_image_used_index = execution_order.size();

        for(uint8_t frame = 0; frame < max_frames_in_flight; frame++){
            for(std::size_t i = 0; i < execution_order.size(); i++){
                auto& sub_group = execution_order[i];
                for(std::size_t j = 0; j < sub_group.size(); j++){
                    auto& ind_sub = sub_group[j];
                    ind_sub->submitInfo[frame].signalSemaphores.clear();

                    //it'll be one signal per queue that's goign to wait on this
                    //CURRENTLY, i'm only setting up graphics
                    if(i == (execution_order.size() - 1)){
                        ind_sub->submitInfo[frame].signalSemaphores.emplace_back(
                            VkSemaphoreSubmitInfo{
                                .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                                .pNext = nullptr,
                                .semaphore = VK_NULL_HANDLE,//binary_semaphores[frame][j],
                                .value = i + 1,
                                .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                                .deviceIndex = 0
                            }
                        );
                        //present_wait_raw_semaphore_data[frame].push_back(binary_semaphores[frame][j].vkSemaphore);
                    }
                    else{
                        ind_sub->submitInfo[frame].signalSemaphores.emplace_back(
                            VkSemaphoreSubmitInfo{
                                .sType = VK_STRUCTURE_TYPE_SEMAPHORE_SUBMIT_INFO,
                                .pNext = nullptr,
                                .semaphore = semaphores[frame][j],
                                .value = i + 1,
                                .stageMask = VK_PIPELINE_STAGE_2_COLOR_ATTACHMENT_OUTPUT_BIT,
                                .deviceIndex = 0
                            }
                        );
                    }
                    if(i > 0){
                        auto& prev_sub_group = execution_order[i - 1];
                        for(std::size_t k = 0; k < prev_sub_group.size(); k++){
                            auto& prev_ind_sub = prev_sub_group[k];
                            //when i eventually add more queues, this will need to reflect that
                            //right now, it doesn't consider queues
                            ind_sub->submitInfo[frame].waitSemaphores.emplace_back(&prev_ind_sub->submitInfo[frame].signalSemaphores[0]);
                        }
                    }
                    if(ind_sub->uses_present_image){
                        if(present_image_used_index > i){
                            present_image_used_index = i;
                        }



                        if(present_image_used_index == i){
                            ind_sub->submitInfo[frame].waitSemaphores.emplace_back( //this is a binary semaphore? waits on acquire
                                &present_wait_semaphore_data[frame]
                            );


                            //present_acquire_waits[frame].push_back(&ind_sub->submitInfo[frame].waitSemaphores.back()->semaphore);
                        }
                    }
                }
            }

            present_wait_raw_semaphore_data[frame].push_back(swapchain.GetCurrentPresentSemaphore());
            presentInfo[frame].waitSemaphoreCount = present_wait_raw_semaphore_data[frame].size();
            presentInfo[frame].pWaitSemaphores = present_wait_raw_semaphore_data[frame].data();
        }
    }

    void RenderGraph::UpdateSemaphores(uint8_t frameIndex){
        for(std::size_t i = 0; i < execution_order.size(); i++){
            if(i != (execution_order.size() - 1)){
                auto& sub_group = execution_order[i];
                for(std::size_t j = 0; j < sub_group.size(); j++){
                    auto& ind_sub = sub_group[j];
                    EWE_ASSERT(ind_sub->submitInfo[frameIndex].signalSemaphores[0].semaphore == semaphores[frameIndex][j].vkSemaphore);

                    ind_sub->submitInfo[frameIndex].signalSemaphores[0].value = semaphores[frameIndex][j].value + 1;
                    semaphores[frameIndex][j].value++;
                }
            }
        }

        present_wait_semaphore_data[frameIndex].semaphore = swapchain.GetAcquireSemaphore(frameIndex);
        present_wait_raw_semaphore_data[frameIndex].back() = swapchain.GetCurrentPresentSemaphore();
        execution_order.back()[0]->submitInfo[frameIndex].signalSemaphores[0].semaphore = present_wait_raw_semaphore_data[frameIndex].back();

    }
}